### ISSUE TITLE
是否允许收录SDK呢？

### ISSUE THREAD

**Issue by freejishu** [Him188/JPRE#3]
（突然想到明明是国人干的为何要用英语23333）
您好，我是来自MyPCQQ官方的freejishu。希望在项目完成后收录进文档，请问是否允许呢？
另外如果可以，可以提供一些技术等相关方面的帮助。
抱歉占用了一个ISSUES，别打我;w;

**Comment by Him188** [comment]
当然可以, 很乐意参与MyPCQQ的开发. 关于"`另外如果可以，可以提供一些技术等相关方面的帮助。`", 我能做到的会尽量帮助

**Comment by freejishu** [comment]
那句话的意思是，如果你需要，我可以提供一些帮助给你。（但请知悉前端狗本人并不会Java）
当然如果出现问题希望可以多沟通。

**Comment by Him188** [comment]
尴尬, 看错了
